CREATE DATABASE PClínicas;

CREATE TABLE PClínicas
(
	idClinica INT PRIMARY KEY IDENTITY
	,RazãoSocial VARCHAR(200) NOT NULL
	,CNPJ VARCHAR(200) NOT NULL
	,Endereço VARCHAR(200) NOT NULL
);

CREATE TABLE Veterinários
(
	idVeterinário INT PRIMARY KEY IDENTITY
	,idClinica  INT FOREIGN  KEY REFERENCES PClínicas(idClinica)
	,Nome VARCHAR(200) NOT NULL
	,CRMV VARCHAR(200) NOT NULL
);

CREATE TABLE Donos
(
	idDono INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL
);

CREATE TABLE TiposPet
(
	idTiposPet INT PRIMARY KEY IDENTITY
	,Descrição VARCHAR(200) NOT NULL
);

CREATE TABLE Raças
(
	idRaça INT PRIMARY KEY IDENTITY
	,idTiposPet INT FOREIGN KEY REFERENCES TiposPet(idTiposPet)
	,Descrição VARCHAR(200) NOT NULL
);

CREATE TABLE Pets
(
	idPets INT PRIMARY KEY IDENTITY
	,idRaça INT FOREIGN KEY REFERENCES Raças(idRaça)
	,idDono INT FOREIGN KEY REFERENCES Donos(idDono)
	,Nome VARCHAR(200) NOT NULL
	,DataDeNascimento VARCHAR(200) NOT NULL
);

CREATE TABLE Atendimentos
(
	idAtendimentos INT PRIMARY KEY IDENTITY
	,idVeterinário INT FOREIGN KEY REFERENCES Veterinários(idVeterinário)
	,idPets INT FOREIGN KEY REFERENCES Pets(idPets)
	,Descrição VARCHAR(200) NOT NULL
	,DataAtendimento VARCHAR(200) NOT NULL
);