CREATE DATABASE PClinicas;

CREATE TABLE PClinicas
(
	idClinica INT PRIMARY KEY IDENTITY
	,RazaoSocial VARCHAR(200) NOT NULL
	,CNPJ VARCHAR(200) NOT NULL
	,Endereco VARCHAR(200) NOT NULL
);

CREATE TABLE Veterinários
(
	idVeterinario INT PRIMARY KEY IDENTITY
	,idClinica  INT FOREIGN  KEY REFERENCES PClínicas(idClinica)
	,Nome VARCHAR(200) NOT NULL
	,CRMV VARCHAR(200) NOT NULL
);

CREATE TABLE Donos
(
	idDono INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL
);

CREATE TABLE TiposPet
(
	idTiposPet INT PRIMARY KEY IDENTITY
	,Descricao VARCHAR(200) NOT NULL
);

CREATE TABLE Racas
(
	idRaca INT PRIMARY KEY IDENTITY
	,idTiposPet INT FOREIGN KEY REFERENCES TiposPet(idTiposPet)
	,Descricao VARCHAR(200) NOT NULL
);

CREATE TABLE Pets
(
	idPets INT PRIMARY KEY IDENTITY
	,idRaca INT FOREIGN KEY REFERENCES Racas(idRaca)
	,idDono INT FOREIGN KEY REFERENCES Donos(idDono)
	,Nome VARCHAR(200) NOT NULL
	,DataDeNascimento VARCHAR(200) NOT NULL
);

CREATE TABLE Atendimentos
(
	idAtendimentos INT PRIMARY KEY IDENTITY
	,idVeterinario INT FOREIGN KEY REFERENCES Veterinarios(idVeterinario)
	,idPets INT FOREIGN KEY REFERENCES Pets(idPets)
	,Descricao VARCHAR(200) NOT NULL
	,DataAtendimento VARCHAR(200) NOT NULL
);