CREATE DATABASE Optus;

USE Optus;

CREATE TABLE Artistas
(
	idArtistas INT PRIMARY KEY IDENTITY
	,Nome	   VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Albuns
(
	idAlbum			INT PRIMARY KEY IDENTITY
	,idArtistas		INT FOREIGN KEY REFERENCES Artistas(idArtistas)
	,Título			VARCHAR(100) NOT NULL
	,DataLancamento VARCHAR(100) NOT NULL
	,Localizacao	VARCHAR(100) NOT NULL
	,QtdMinutos		VARCHAR(100) NOT NULL
	,Ativo			VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Estilos
(
	idEstilos INT PRIMARY KEY IDENTITY
	,Nome	  VARCHAR(100) NOT NULL
);
GO

CREATE TABLE AlbunsEstilos
(
	idAlbum		INT FOREIGN KEY REFERENCES Albuns(idAlbum)
	,idEstilos	INT FOREIGN KEY REFERENCES Estilos(idEstilos)
);
GO

CREATE TABLE Usuarios
(
	idUsuario	INT PRIMARY KEY IDENTITY
	,Nome		VARCHAR(100) NOT NULL
	,Email		VARCHAR(100) NOT NULL
	,Senha		VARCHAR(100) NOT NULL
	,Permissao	VARCHAR(100) NOT NULL
);
GO